apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadxtgt4992-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadxtgt4992-tenant-component
    app.kubernetes.io/part-of: loadxtgt4992-tenant-app
  name: loadxtgt4992-tenant-component
  namespace: loadxtgt4992-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadxtgt4992-tenant-component
    weight: null
status: {}
